language: ruby
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
  - secure: "zV6WTvU322sfPIROQI683fvGZNhqhP6oUA4+xXWN4ssULucu/oX2aQ9NkvfV/8IcJHykj0wDtkm8bxrHie80G1QOUsa/ZBHMy3X0KyRg/5dmgBQWShT27koYsO9g15uOvagCDWf3Kj3eE3JGdsWk6JWMx83D2nbVmgV/iMf4tX8="
