language: ruby
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
  - secure: EIgEDaJ1DCRrSTPvGQNVHWOxAQmY+2CJRRZcf/fdrZamA6PisIv+XTWUUVg+koEq26/Ys5p0MSyOyKhO/2VRQrBqFq5PnlW1oN5c5jJZg4u3Oj4dhL4y93xIvYS6zZLpDQMerTc4dlpzZSshA2dz3sm5mRttAgLvpN9lO0H+448=
