language: ruby

install:
  # Install Jekyll and dependencies
  - bundle install

script: bundle exec rake site:deploy --quiet

env:
  global:
    secure:  "mtXLp+jRno6htakZIWCojHfIYNwkfpru8RrKHndEgT8dTw59RqDfXRLyfPZATtNJRqU/Ty6aTmA9OCjeB+tY6lzMEgsSAgaiz6RXw5PlhVNPZCqmz58DrUHDRS4w7Zzj2KOQgHYalx7fuXTS6lPXfO6zhU92jtCmx/2rKkzIgtk="