language: ruby
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
  - secure: "W5Sx37mP9zuHB7ysGGQXX22+6xYXzd9+ANmQgvrF3QsDFY2wfk11pm9r4nEVMMOs2frXPrHB484a+0KGFrKRmWR7Rw82dR0fwtJqtTl1Oc6FCU0cGJrwqFszVJxBHGiNKgwv5+xgj4EEQzC1X+Ogp01wa6ZjjD5mxDo1cao1SXg="
