language: ruby
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
  - secure: "Ucbo/9jf7Dd0vhIqKqaBYjDnxufRKPZqrKQaRUv1W3yWiokQT840tqB7Z0OtvDjn5bmIpzHKMIUy4sr8XZY7qRVrzyNqtxLykyUDYfzQl2V/fTl9rZq26HNavYEv/Ssi6UQ8esP12FGIuNUARN8Cby9XC7/Kim7GpzaG/Yd+vcw="
