markdown: kramdown
kramdown:
  entity_output: as_input
exclude: [Gemfile, Gemfile.lock, planet.yml]
auto_permalinks: true 
name: Tim Videos - Live Event Streaming - Developers page
description: News, informations, instructions and how to contribute
url: http://code.timvideos.us
permalink: pretty
highlighter: pygments

edit_interface_link: https://github.com/pinoss/getting-started/edit/master/((filename)) 