markdown: kramdown
kramdown:
  entity_output: as_input
exclude: [Gemfile, Gemfile.lock, planet.yml]
name: Tim Videos - Live Event Streaming - Developers page
description: News, informations, instructions and how to contribute
url: http://code.timvideos.us
permalink: pretty
highlighter: pygments
prose:
  repo_name: pinoss-getting-started
  branch: master
  prose_url: http://pinoss.github.io/prose
  site_url: http://pinoss.github.io
  ignore: 
    - _generate.sh
    - _config.yml