username: timvideos
repo: hdmi2usb.tv
branch: master

safe: false
lsi: false

markdown: kramdown
kramdown:
  entity_output: as_input
exclude: [Gemfile, Gemfile.lock, planet.yml, vendor, .travis.yml, Rakefile, README.md, DEPLOY.md]
auto_permalinks: true 
name: HDMI2USB - Open source for live event capture
description: 
url: http://hdmi2usb.tv/
permalink: pretty
highlighter: pygments

edit_interface_link: 'http://editor.timvideos.us/#timvideos/hdmi2usb.tv/edit/master/((filename))'

prose:
  siteurl: 'http://hdmi2usb.tv'
  relativeLinks: 'http://hdmi2usb.tv/links.jsonp'
