markdown: kramdown
kramdown:
  entity_output: as_input
exclude: [Gemfile, Gemfile.lock, planet.yml]
auto_permalinks: true 
name: Tim Videos - Live Event Streaming - Developers page
description: News, informations, instructions and how to contribute
url: http://code.timvideos.us
permalink: pretty
highlighter: pygments
prose:
  rooturl: '_includes'
  siteurl: 'http://pinoss.github.io/'
  relativeLinks: 'http://pinoss.github.io/links.jsonp'
  media: 'img'
  metadata:
    _includes:
      - name: "category"
        field:
          element: "hidden"
          value: "blog"
      - name: "layout"
        field:
          element: "hidden"
          value: "blog"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "splash"
        field:
          element: "text"
          label: "Splash image"
          value: ""
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Apples"
              value: "apples"
            - name: "Bananas"
              value: "bananas"
            - name: "Pears"
              value: "pears"
            - name: "Mangos"
              value: "mangos"
