username: timvideos
repo: getting-started
branch: master

destination: ../getting-started-gh-pages/

safe: false
lsi: false

markdown: kramdown
kramdown:
  entity_output: as_input
exclude: [Gemfile, Gemfile.lock, planet.yml, vendor, .travis.yml, Rakefile]
auto_permalinks: true 
name: Tim Videos - Live Event Streaming - Developers page
description: News, informations, instructions and how to contribute
url: http://code.timvideos.us
permalink: pretty
highlighter: pygments

edit_interface_link: 'http://editor.timvideos.us/#timvideos/getting-started/edit/master/((filename))' 

prose:
  siteurl: 'http://code.timvideos.us'
  relativeLinks: 'http://code.timvideos.us/links.jsonp'
